== Log into the serial port console

This challenge will be run from the `+Serial Port+` tab which is a
serial port console.

Hit enter on your keyboard to bring up the login prompt.

Login as the user `+rhel+`.

[source,bash,run]
----
rhel
----

Enter the password `+redhat+`.

[source,bash,run]
----
redhat
----

Change to the super user account.

[source,bash,run]
----
sudo -i
----

== Run the upgrade

Now that you have verified the RHEL system meets all the expected
conditions, it is time to kick off the upgrade process: (Note: This
process will take awhile.)

[source,bash,run]
----
leapp upgrade --target 9.5 --reboot
----

Leapp is performing several actions inside a temporary environment. This
includes creating a new initramfs image, relabeling SELinux contexts,
and well as cleaning up any remaining RHEL 8 packages. Included is a
reboot process that can take up to 15 minutes.

== Verify the upgrade

Once the new initramfs image is in place, package updates run, and
SELinux relabel completion, the system will perform one final reboot.

Once that is done, you must log into the system’s terminal.

Log in with this username.

[source,bash,run]
----
rhel
----

Enter this password.

[source,bash,run]
----
redhat
----

Finally, we will verify the update was successful by looking at the
release file we referenced earlier in the lab:

Run the following command in the `+RHEL+` terminal.

[source,bash,run]
----
cat /etc/redhat-release
----

Note that we are now running the latest version of RHEL 9!

OPTIONAL: You may also review the log file if you so choose. The full
output is available at /var/log/leapp/leapp-upgrade.log

[source,bash,run]
----
sudo less /var/log/leapp/leapp-upgrade.log
----

There are other methods for upgrading to the latest version of RHEL
using the leapp tooling including the Web Console and Satellite. For
those operations, refer to the documentation on Red Hat’s website.
