---
virtualmachines:
  - name: "host"
    image: "rhel-8.10"
    # bootloader: efi
    memory: "4G"
    cores: 1
    image_size: "40G"
    consoles:
      - name: console-host
        command: virtctl console host
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
